// apps/angular-demo/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import { RouterModule } from '@angular/router';

import { LineChartComponent } from 'ngx-sparklib';

import {
  datumLine,
  lineChart,
  lineProperties,
  linearGradient,
  margins,
  stripeChart,
} from 'sparklib';
import {
  monoDataValues,
  monotonicIncreasing,
  pairDataValues,
  pairSegmentValues,
  randomInRange,
  singleValues,
  stripe_x10_0_and_1,
  stripe_x10_0_to_9,
  stripe_x10_1_and_0,
  stripe_x10_mostly_0,
  stripe_x10_mostly_1,
} from './data';

@Component({
  standalone: true,
  imports: [LineChartComponent, RouterModule],
  selector: 'sparklib-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements AfterViewInit {
  @ViewChild('container') container: ElementRef<HTMLDivElement> | undefined;

  monoDataValues = monoDataValues;
  pairDataValues = pairDataValues;
  pairSegmentValues = pairSegmentValues;

  marginsBuilder = margins().bottom(25).left(25).right(25).top(25);
  margins = margins().bottom(5).left(5).right(5).top(5).build();

  prideColors: string[] = [
    '#ed2224',
    '#f35b22',
    '#f99621',
    '#f5c11e',
    '#f1eb1b',
    '#f1eb1b',
    '#f1eb1b',
    '#63c720',
    '#0c9b49',
    '#21878d',
    '#3954a5',
    '#61379b',
    '#93288e',
  ];

  redColors = [
    '#ffffff',
    '#fff5f0',
    '#fee0d2',
    '#fcbba1',
    '#fc9272',
    '#fb6a4a',
    '#ef3b2c',
    '#cb181d',
    // '#a50f15',
    // '#67000d',
  ];

  prideGradient = linearGradient(0, 0, 250, 0)
    .addColorStop(0.077, '#ed2224')
    .addColorStop(0.154, '#f35b22')
    .addColorStop(0.231, '#f99621')
    .addColorStop(0.308, '#f5c11e')
    .addColorStop(0.385, '#f1eb1b')
    .addColorStop(0.462, '#f1eb1b')
    .addColorStop(0.539, '#f1eb1b')
    .addColorStop(0.616, '#63c720')
    .addColorStop(0.693, '#0c9b49')
    .addColorStop(0.77, '#21878d')
    .addColorStop(0.847, '#3954a5')
    .addColorStop(0.924, '#61379b')
    .addColorStop(1, '#93288e');

  hGradientBuilder = linearGradient(0, 0, 250, 0)
    .addColorStop(0, 'blue')
    .addColorStop(1, 'lightgreen');

  hGradient = linearGradient(0, 0, 250, 0)
    .addColorStop(0, 'lightgreen')
    .addColorStop(1, 'black')
    .build();

  vGradient = linearGradient(0, 0, 0, 50)
    .addColorStop(0, 'yellow')
    .addColorStop(1, 'red');

  ngAfterViewInit(): void {
    const chart0 = lineChart()
      .width(150)
      .height(250)
      .margins({ bottom: 0, left: 0, right: 0, top: 0 })
      .yDatum(0, { lineDash: [1, 1], strokeStyle: 'gray' })
      .yDatum(5)
      .yDatum(-5)
      .yDomain([-10, 10])
      .render(singleValues);

    const chart1 = lineChart()
      .width(150)
      .height(250)
      .margins(margins().bottom(10).left(10).right(10).top(10))
      .yDatum(0, { lineDash: [1, 1], strokeStyle: 'gray' })
      .yDatum(5)
      .yDatum(-5)
      .yDomain([-10, 10])
      .render(singleValues);

    const chart2 = lineChart()
      .width(150)
      .height(250)
      .margins(margins().bottom(10).left(10).right(10).top(10))
      .xDatum(
        datumLine(
          10,
          lineProperties()
            .setLineDash([2, 2])
            .setStrokeStyle(
              linearGradient(10, 0, 10, 250)
                .addColorStop(0, 'blue')
                .addColorStop(1, 'lightgreen'),
            ),
        ),
      )
      .yDatum(
        datumLine(
          0,
          lineProperties()
            .setLineDash([1, 1])
            .setLineWidth(1)
            .setStrokeStyle('gray'),
        ),
      )
      .yDatum(5)
      .yDatum(-5)
      .yDomain([-10, 10])
      .render(singleValues);

    const stripeChart0 = stripeChart()
      .width(stripe_x10_1_and_0.length * 4)
      .height(25)
      .render(stripe_x10_1_and_0);

    const stripeChart1 = stripeChart()
      .width(stripe_x10_mostly_0.length * 4)
      .height(25)
      .render(stripe_x10_mostly_0);

    const stripeChart2 = stripeChart()
      .width(stripe_x10_0_and_1.length * 4)
      .height(25)
      .render(stripe_x10_0_and_1);

    const stripeChart3a = stripeChart()
      .width(stripe_x10_mostly_1.length * 4)
      .height(25)
      .render(stripe_x10_mostly_1);

    const stripeChart3b = stripeChart()
      .width(stripe_x10_0_to_9.length * 4)
      .height(25)
      .render(stripe_x10_0_to_9);

    const monotonic100 = monotonicIncreasing(0, 100);
    const monotonicDay = monotonicIncreasing(0, 24 * 60);
    const randomDay1 = randomInRange(0, 5, 24 * 60, 0);
    const randomDay2 = randomInRange(0, 5, 24 * 60, 0.8);

    const stripeChart4 = stripeChart()
      .width(monotonic100.length * 2)
      .height(25)
      .gradientColors(['red', 'green', 'blue'], 3)
      .render(monotonic100);

    const stripeChart5 = stripeChart()
      .width(monotonicDay.length)
      .height(25)
      .gradientColors(['red', 'green', 'blue'])
      .render(monotonicDay);

    const stripeChart6 = stripeChart()
      .width(monotonicDay.length)
      .height(25)
      .gradientColors(this.prideColors, monotonicDay.length)
      .render(monotonicDay);

    const stripeChart7 = stripeChart()
      .width(monotonicDay.length)
      .height(25)
      .gradientColors(this.prideColors, 40)
      .render(monotonicDay);

    const stripeChart8a = stripeChart()
      .width(randomDay1.length)
      .height(25)
      .gradientColors(this.prideColors)
      .render(randomDay1);

    const stripeChart8b = stripeChart()
      .width(randomDay1.length / 4)
      .height(25)
      .gradientColors(this.prideColors)
      .render(randomDay1);

    const stripeChart9a = stripeChart()
      .width(randomDay2.length)
      .height(25)
      .gradientColors(this.redColors, this.redColors.length)
      .render(randomDay2);

    const stripeChart9b = stripeChart()
      .width(randomDay2.length / 4)
      .height(25)
      .gradientColors(this.redColors, this.redColors.length)
      .render(randomDay2);

    this.#append(stripeChart0, 'stripeChart0', true);
    this.#append(stripeChart1, 'stripeChart1', true);
    this.#append(stripeChart2, 'stripeChart2', true);
    this.#append(stripeChart3a, 'stripeChart3a', true);
    this.#append(stripeChart3b, 'stripeChart3b', true);
    this.#append(stripeChart4, 'stripeChart4');
    this.#append(stripeChart5, 'stripeChart5');
    this.#append(stripeChart6, 'stripeChart6');
    this.#append(stripeChart7, 'stripeChart7');
    this.#append(stripeChart8a, 'stripeChart8a');
    this.#append(stripeChart8b, 'stripeChart8b');
    this.#append(stripeChart9a, 'stripeChart9a');
    this.#append(stripeChart9b, 'stripeChart9b');

    this.#append(chart0, 'chart0');
    this.#append(chart1, 'chart1');
    this.#append(chart2, 'chart2');
  }

  #append(chart: HTMLCanvasElement, label: string, border = true) {
    const div = document.createElement('div');
    div.textContent = label;
    this.container?.nativeElement.appendChild(div);

    this.container?.nativeElement.appendChild(chart);

    if (border) {
      chart.style.borderWidth = '1px';
      chart.style.borderStyle = 'solid';
      chart.style.borderColor = 'lightgray';
      chart.style.margin = '4px';
    }

    this.container?.nativeElement.appendChild(chart);
  }
}

<table>
  <thead>
    <tr>
      <th>Country</th>
      <td></td>
      <th>City</th>
      <!-- <td></td>
      <th>Station</th>
      <td></td>
      <th>From Date</th>
      <th>To Date</th> -->
      <td></td>
      <th>Max °C</th>
      <th>Min °C</th>
      <th>Demo 1</th>
      <th>Demo 2</th>
      <th>Demo 3</th>
    </tr>
  </thead>
  <tbody>
    <!-- Loop through records -->
    <tr *ngFor="let record of weatherRecords; let i = index">
      <td>{{ record.country }}</td>
      <td></td>
      <td>{{ record.city }}</td>
      <!-- <td></td>
      <td>{{ record.stationNumber }}</td>
      <td></td>
      <td>{{ record.fromDate }}</td>
      <td>{{ record.toDate }}</td> -->
      <td></td>
      <td>
        <sparklib-line-chart
          [width]="record.maxT.length"
          [height]="lineChartHeight"
          [margins]="{ top: 0, bottom: 0, left: 0, right: 0 }"
          [yDomain]="[-15, 45]"
          [background]="'lightyellow'"
          [yDatumLines]="yDatumLines"
          [values]="record.maxT"
          [mouseEventTypes]="[MouseEventType.Click, MouseEventType.MouseOver]"
          (mouseEvent)="handleMouseEvent($event, i)"
        ></sparklib-line-chart>
      </td>
      <td>
        <sparklib-line-chart
          [width]="record.maxT.length"
          [height]="lineChartHeight"
          [margins]="{ top: 0, bottom: 0, left: 0, right: 0 }"
          [yDomain]="[-15, 45]"
          [background]="'lightyellow'"
          [fillStyle]="simpleTemperatureGradient"
          [values]="record.minT"
        ></sparklib-line-chart>
      </td>
      <td>
        <sparklib-line-chart
          [width]="record.maxT.length"
          [height]="lineChartHeight"
          [margins]="{ top: 0, bottom: 0, left: 0, right: 0 }"
          [yDomain]="[0, 45]"
          [background]="'lightyellow'"
          [fillStyle]="hGradient"
          [values]="record.meanT"
        ></sparklib-line-chart>
      </td>
      <td>
        <sparklib-line-chart
          [width]="record.maxT.length"
          [height]="lineChartHeight"
          [margins]="{ top: 0, bottom: 0, left: 0, right: 0 }"
          [yDomain]="[0, 45]"
          [background]="'lightyellow'"
          [fillStyle]="prideGradient"
          [values]="record.maxT"
        ></sparklib-line-chart>
      </td>
      <td>
        <sparklib-line-chart
          [width]="record.maxT.length"
          [height]="lineChartHeight"
          [margins]="{ top: 0, bottom: 0, left: 0, right: 0 }"
          [yDomain]="[0, 45]"
          [background]="'lightyellow'"
          [fillStyle]="simpleTemperatureGradient"
          [values]="record.maxT"
        ></sparklib-line-chart>
      </td>
    </tr>
  </tbody>
</table>
<span class="credits">{{ credits }}</span>
<br />
<br />
<hr />

<sparklib-line-chart
  id="mouse-over-chart"
  [width]="250"
  [height]="100"
  [margins]="{ top: 0, bottom: 0, left: 10, right: 10 }"
  [background]="'lightyellow'"
  [values]="monoDataValues"
></sparklib-line-chart>

<sparklib-line-chart
  style="margin-left: 5px"
  [width]="250"
  [height]="100"
  [margins]="marginsBuilder"
  [background]="hGradientBuilder"
  [values]="monoDataValues"
></sparklib-line-chart>

<sparklib-line-chart
  style="margin-left: 5px"
  [width]="250"
  [height]="100"
  [margins]="marginsBuilder"
  [background]="prideGradient"
  [values]="monoDataValues"
></sparklib-line-chart>

<br />
<hr />
<br />
Object arrays
<sparklib-line-chart
  style="margin-left: 5px"
  [width]="250"
  [height]="100"
  [margins]="marginsBuilder"
  [background]="prideGradient"
  [values]="monoObjectValuesWithGaps"
  [yAccessor]="yAccessor"
></sparklib-line-chart>

<sparklib-line-chart
  style="margin-left: 5px"
  [background]="'lightgray'"
  [margins]="{ top: 10, bottom: 10, left: 10, right: 10 }"
  [strokeStyle]="hGradient"
  [values]="pairObjectSegmentValues"
  [xAccessor]="xAccessor"
  [yAccessor]="yAccessor"
></sparklib-line-chart>
<br />
<hr />
<br />

<sparklib-line-chart
  [margins]="{ top: 10, bottom: 10, left: 10, right: 10 }"
  [background]="'lightgreen'"
  [values]="pairDataValues"
></sparklib-line-chart>
<sparklib-line-chart
  style="margin-left: 5px"
  [margins]="margins"
  [background]="vGradient"
  [values]="pairDataValues"
></sparklib-line-chart>
<br />
<sparklib-line-chart
  [background]="'lightgray'"
  [margins]="{ top: 10, bottom: 10, left: 10, right: 10 }"
  [values]="pairSegmentValues"
></sparklib-line-chart>

<sparklib-line-chart
  [background]="'lightgray'"
  [margins]="{ top: 10, bottom: 10, left: 10, right: 10 }"
  [values]="monoDataValuesWithGaps"
></sparklib-line-chart>

<sparklib-line-chart
  style="margin-left: 5px"
  [background]="'lightgray'"
  [margins]="{ top: 10, bottom: 10, left: 10, right: 10 }"
  [strokeStyle]="hGradient"
  [values]="pairSegmentValues"
></sparklib-line-chart>
<br />
<sparklib-line-chart
  [width]="250"
  [height]="100"
  [margins]="{ top: 0, bottom: 0, left: 10, right: 10 }"
  [background]="'lightyellow'"
  [fillStyle]="'black'"
  [values]="monoDataValues"
></sparklib-line-chart>
<sparklib-line-chart
  style="margin-left: 5px"
  [width]="250"
  [height]="100"
  [margins]="{ top: 0, bottom: 0, left: 10, right: 10 }"
  [background]="'lightyellow'"
  [fillStyle]="hGradient"
  [values]="monoDataValues"
></sparklib-line-chart>
<br />
<hr />

<span>stripe0</span><br />
<sparklib-stripe-chart
  class="stripe-chart"
  [width]="stripe_x10_1_and_0.length * 4"
  [height]="25"
  [values]="stripe_x10_1_and_0"
  [mouseEventTypes]="[MouseEventType.Click, MouseEventType.MouseOver]"
  (mouseEvent)="handleStripeChartMouseEvent($event)"
></sparklib-stripe-chart>
<br />
<span>stripe1</span><br />
<sparklib-stripe-chart
  class="stripe-chart"
  [width]="stripe_x10_mostly_0.length * 4"
  [height]="25"
  [values]="stripe_x10_mostly_0"
></sparklib-stripe-chart>
<router-outlet></router-outlet>

<hr />
<div #container class="container"></div>
<hr />

<div>AxisPosition.Top</div>
<br />
<sparklib-axis
  [position]="AxisPosition.Top"
  [width]="250"
  [height]="30"
  [lineWidth]="2"
  [font]="'11px arial'"
  [fontColor]="'blue'"
  [ticks]="ticks0"
  [tickPadding]="4"
  [tickLength]="15"
  [tickWidth]="1"
></sparklib-axis>
<br />
<br />
<br />
<div>AxisPosition.Bottom</div>
<br />
<sparklib-axis
  [position]="AxisPosition.Bottom"
  [width]="250"
  [height]="30"
  [lineWidth]="3"
  [font]="'16px arial'"
  [ticks]="ticks1"
></sparklib-axis>

<br />
<br />
<br />
<div>AxisPosition.Left</div>
<br />
<sparklib-axis
  [position]="AxisPosition.Left"
  [width]="40"
  [height]="250"
  [lineWidth]="3"
  [font]="'bold 11px arial'"
  [fontColor]="'blue'"
  [ticks]="ticks0"
></sparklib-axis>

<br />
<br />
<br />
<div>AxisPosition.Right</div>
<br />
<sparklib-axis
  [position]="AxisPosition.Right"
  [width]="40"
  [height]="250"
  [lineWidth]="1"
  [ticks]="ticks1"
></sparklib-axis>

<br />
<br />
<br />
<div>Fancy AxisPosition.Bottom</div>
<br />
<sparklib-axis
  [position]="AxisPosition.Bottom"
  [width]="250"
  [height]="30"
  [strokeStyle]="'blue'"
  [lineWidth]="3"
  [font]="'16px arial'"
  [ticks]="ticks1"
></sparklib-axis>

<br />
<br />
<br />
<div>Very Fancy AxisPosition.Bottom</div>
<br />
<sparklib-axis
  [position]="AxisPosition.Bottom"
  [width]="250"
  [height]="30"
  [strokeStyle]="hGradient"
  [lineWidth]="3"
  [font]="'16px arial'"
  [fontColor]="'green'"
  [ticks]="ticks1"
></sparklib-axis>

<hr />
<div class="simple-axis-chart-container" *ngIf="weatherRecords[0]">
  <sparklib-axis
    class="plain-axis-chart"
    [position]="AxisPosition.Top"
    [width]="weatherRecords[0].maxT.length"
    [height]="20"
    [background]="'lightyellow'"
    [font]="'10px arial'"
    [ticks]="axisChartTopTicks"
    [tickPadding]="4"
    [tickWidth]="1"
  ></sparklib-axis>
  <sparklib-line-chart
    class="plain-axis-chart"
    [width]="weatherRecords[0].maxT.length"
    [height]="lineChartHeight"
    [yDomain]="[0, 45]"
    [background]="'lightyellow'"
    [fillStyle]="'lightgreen'"
    [values]="weatherRecords[0].maxT"
  ></sparklib-line-chart>
</div>
<hr />

<div *ngIf="weatherRecords[0]">
  <table
    id="capture"
    style="background-color: lightyellow"
    [cellPadding]="0"
    [cellSpacing]="0"
  >
    <tr>
      <!-- font-size: 0 removes the vertical space from inline-block content  -->
      <td colspan="3" style="text-align: center; font-size: 0">
        <sparklib-axis
          style="display: inline-block"
          class="plain-axis-chart"
          [position]="AxisPosition.Top"
          [width]="weatherRecords[0].maxT.length + 2"
          [height]="20"
          [background]="'lightyellow'"
          [font]="'10px arial'"
          [ticks]="ticks1"
          [tickPadding]="4"
          [tickWidth]="1"
        ></sparklib-axis>
      </td>
    </tr>
    <tr>
      <td>
        <sparklib-axis
          class="plain-axis-chart"
          [position]="AxisPosition.Left"
          [width]="30"
          [height]="weatherRecords[0].maxT.length"
          [background]="'lightyellow'"
          [font]="'10px arial'"
          [ticks]="ticks1"
          [tickPadding]="4"
          [tickWidth]="1"
        ></sparklib-axis>
      </td>
      <td>
        <sparklib-line-chart
          [width]="243"
          [height]="243"
          [background]="'lightyellow'"
          [fillStyle]="'lightgreen'"
          [yDomain]="[0, 45]"
          [values]="weatherRecords[0].maxT"
        >
        </sparklib-line-chart>
      </td>
      <td>
        <sparklib-axis
          class="plain-axis-chart"
          [position]="AxisPosition.Right"
          [width]="30"
          [height]="weatherRecords[0].maxT.length"
          [background]="'lightyellow'"
          [font]="'10px arial'"
          [ticks]="ticks1"
          [tickPadding]="4"
          [tickWidth]="1"
        ></sparklib-axis>
      </td>
    </tr>
    <tr>
      <td colspan="3" style="text-align: center">
        <sparklib-axis
          style="display: inline-block"
          class="plain-axis-chart"
          [position]="AxisPosition.Bottom"
          [width]="weatherRecords[0].maxT.length + 2"
          [height]="20"
          [background]="'lightyellow'"
          [font]="'10px arial'"
          [ticks]="ticks1"
          [tickPadding]="4"
          [tickWidth]="1"
        ></sparklib-axis>
      </td>
    </tr>
  </table>
  <br />
  <button (click)="capture()">Capture</button>
</div>

// apps/react-demo/src/app/app.tsx
import * as sparklib from 'react-sparklib';

const data: [number, number][] = [
  [1, 2],
  [2, 3],
  [3, 4],
  [4, 5],
  [5, 6],
  [6, 6],
  [7, 6],
  [8, 6],
  [9, 6],
  [10, 6],
];

const data2: number[] = [1, 50, 10, 70, 1, 0, 1, 20, 1, 0];

export interface DataObject {
  xPos: number;
  yPos: number | null;
  someOtherProp: string;
}

export interface StripeDataObject {
  value: number;
  someOtherProp: string;
}

export const pairObjectSegmentValues: DataObject[] = [
  { xPos: 0, yPos: 7.64, someOtherProp: 'data' },
  { xPos: 10, yPos: -5.42, someOtherProp: 'data' },
  { xPos: 20, yPos: 11.89, someOtherProp: 'data' },
  { xPos: 30, yPos: -1.33, someOtherProp: 'data' },
  { xPos: 40, yPos: 3.52, someOtherProp: 'data' },
  { xPos: 50, yPos: -10.7, someOtherProp: 'data' },
  { xPos: 60, yPos: 8.25, someOtherProp: 'data' },
  { xPos: 70, yPos: 14.03, someOtherProp: 'data' },
  { xPos: 80, yPos: -4.97, someOtherProp: 'data' },
  { xPos: 90, yPos: null, someOtherProp: 'empty' },
  { xPos: 100, yPos: null, someOtherProp: 'empty' },
  { xPos: 110, yPos: 12.23, someOtherProp: 'data' },
  { xPos: 120, yPos: 2.64, someOtherProp: 'data' },
  { xPos: 130, yPos: -7.89, someOtherProp: 'data' },
  { xPos: 140, yPos: 5.97, someOtherProp: 'data' },
  { xPos: 150, yPos: null, someOtherProp: 'empty' },
  { xPos: 160, yPos: 8.0, someOtherProp: 'data' },
  { xPos: 170, yPos: null, someOtherProp: 'empty' },
  { xPos: 180, yPos: 9.36, someOtherProp: 'data' },
  { xPos: 190, yPos: -2.91, someOtherProp: 'data' },
  { xPos: 200, yPos: 1.78, someOtherProp: 'data' },
  { xPos: 210, yPos: -8.32, someOtherProp: 'data' },
  { xPos: 220, yPos: 13.56, someOtherProp: 'data' },
  { xPos: 230, yPos: -6.15, someOtherProp: 'data' },
];

export const randomObjectsInRange = (
  minV: number,
  maxV: number,
  length: number,
  zeroProbability: number,
): StripeDataObject[] => {
  const result: StripeDataObject[] = [];

  for (let i = 0; i < length; ++i) {
    const randomNum = parseFloat(Math.random().toFixed(1));

    if (randomNum < zeroProbability) {
      result.push({ value: 0, someOtherProp: 'zero' });
    } else {
      result.push({
        value: randomNum * (maxV - minV) + minV,
        someOtherProp: `random-${i}`,
      });
    }
  }

  return result;
};

const prideGradient = sparklib
  .linearGradient(0, 0, 250, 0)
  .addColorStop(0.077, '#ed2224')
  .addColorStop(0.154, '#f35b22')
  .addColorStop(0.231, '#f99621')
  .addColorStop(0.308, '#f5c11e')
  .addColorStop(0.385, '#f1eb1b')
  .addColorStop(0.462, '#f1eb1b')
  .addColorStop(0.539, '#f1eb1b')
  .addColorStop(0.616, '#63c720')
  .addColorStop(0.693, '#0c9b49')
  .addColorStop(0.77, '#21878d')
  .addColorStop(0.847, '#3954a5')
  .addColorStop(0.924, '#61379b')
  .addColorStop(1, '#93288e');

const gradientColors = [
  '#ed2224',
  '#f35b22',
  '#f99621',
  '#f5c11e',
  '#f1eb1b',
  '#f1eb1b',
  '#f1eb1b',
  '#63c720',
  '#0c9b49',
  '#21878d',
  '#3954a5',
  '#61379b',
  '#93288e',
];

const redColors = [
  '#ffffff',
  '#fff5f0',
  '#fee0d2',
  '#fcbba1',
  '#fc9272',
  '#fb6a4a',
  '#ef3b2c',
  '#cb181d',
  // '#a50f15',
  // '#67000d',
];

const hGradient = sparklib
  .linearGradient(0, 0, 250, 0)
  .addColorStop(0, 'lightgreen')
  .addColorStop(1, 'black');

const randomObjectsDay2 = randomObjectsInRange(0, 5, 24 * 60, 0.8);

const ticks0: sparklib.AxisTick[] = [
  { label: '0', position: 0 },
  { label: '', position: 62 },
  { label: '125', position: 125 },
  { label: '', position: 188 },
  { label: '250', position: 250 },
];

const ticks1: sparklib.AxisTick[] = [
  { label: '25', position: 25 },
  { label: '', position: 75 },
  { label: '125', position: 125 },
  { label: '', position: 175 },
  { label: '225', position: 225 },
];

export function App() {
  const xAccessor = (data: DataObject): number | null => data.xPos;
  const yAccessor = (data: DataObject): number | null => data.yPos;
  const handleMouseEvent = (event: sparklib.ChartMouseEvent) =>
    console.log(
      `${event.eventType} [${event.startIndex}/${event.endIndex}]: (${event.x},${event.y})`,
      event,
    );

  return (
    <div className="App">
      <sparklib.LineChart
        values={data}
        background={prideGradient}
        lineWidth={2}
        lineDash={[2, 2, 10]}
        strokeStyle={hGradient}
        yDomain={[2, 6]}
      />
      <br />
      <hr />
      <sparklib.LineChart<DataObject>
        values={pairObjectSegmentValues}
        xAccessor={xAccessor}
        yAccessor={yAccessor}
        background={'lightgray'}
        margins={{ top: 10, bottom: 10, left: 10, right: 10 }}
        strokeStyle={hGradient}
        mouseEventTypes={[
          sparklib.MouseEventType.Click,
          sparklib.MouseEventType.MouseOver,
        ]}
        onMouseEvent={handleMouseEvent}
      />
      <br />
      <hr />
      <sparklib.BarChart
        values={data2}
        background="lightyellow"
        fillStyle={hGradient}
      />
      <br />
      <hr />
      <sparklib.StripeChart
        values={data2}
        width={150}
        gradientColors={gradientColors}
        nGradientColorLevels={2}
      />
      <br />
      <hr />
      <sparklib.StripeChart<StripeDataObject>
        values={randomObjectsDay2}
        valueAccessor={(data: StripeDataObject): number => data.value}
        height={25}
        width={randomObjectsDay2.length}
        gradientColors={redColors}
        nGradientColorLevels={2}
        mouseEventTypes={[
          sparklib.MouseEventType.Click,
          sparklib.MouseEventType.MouseOver,
        ]}
        onMouseEvent={handleMouseEvent}
      />
      <br />
      <hr />
      <div>AxisPosition.Top</div>
      <br />
      <sparklib.Axis
        position={sparklib.AxisPosition.Top}
        width={250}
        height={30}
        lineWidth={2}
        font="11px arial"
        fontColor="blue"
        ticks={ticks0}
        tickPadding={4}
        tickLength={15}
        tickWidth={1}
      ></sparklib.Axis>
      <br />
      <br />
      <br />
      <div>AxisPosition.Bottom</div>
      <br />
      <sparklib.Axis
        position={sparklib.AxisPosition.Bottom}
        width={250}
        height={30}
        lineWidth={3}
        font="16px arial"
        ticks={ticks1}
      ></sparklib.Axis>
      <br />
      <br />
      <br />
      <div>AxisPosition.Left</div>
      <br />
      <sparklib.Axis
        position={sparklib.AxisPosition.Left}
        width={40}
        height={250}
        lineWidth={3}
        font="bold 11px arial"
        fontColor="blue"
        ticks={ticks0}
      ></sparklib.Axis>
      <br />
      <br />
      <br />
      <div>AxisPosition.Left</div>
      <br />
      <sparklib.Axis
        position={sparklib.AxisPosition.Right}
        width={40}
        height={250}
        ticks={ticks1}
      ></sparklib.Axis>
      <br />
      <br />
      <br />
      <br />
      <div>Fancy AxisPosition.Bottom</div>
      <br />
      <sparklib.Axis
        position={sparklib.AxisPosition.Bottom}
        width={250}
        height={30}
        strokeStyle={hGradient}
        lineWidth={3}
        font="16px arial"
        fontColor="green"
        ticks={ticks1}
      ></sparklib.Axis>
      <hr />
    </div>
  );
}

export default App;
