// packages/ngx-sparklib/src/lib/axis.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  Axis,
  AxisChartProperties,
  AxisPosition,
  AxisTick,
  LinearGradient,
  LinearGradientBuilder,
  axis,
} from 'sparklib';

@Component({
  selector: 'sparklib-axis',
  standalone: true,
  imports: [CommonModule],
  template: '<canvas #canvasRef></canvas>',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AxisComponent implements AfterViewInit {
  @Input() width?: number;
  @Input() height?: number;
  @Input() dpi?: number;
  @Input() background?: string | LinearGradient | LinearGradientBuilder;
  @Input() position?: AxisPosition;
  @Input() font?: string;
  @Input() fontColor?: string;
  @Input() lineWidth?: number;
  @Input() ticks?: AxisTick[];
  @Input() tickLength?: number;
  @Input() tickWidth?: number;
  @Input() tickPadding?: number;
  @Input() properties?: AxisChartProperties;

  @ViewChild('canvasRef') canvasRef!: ElementRef<HTMLCanvasElement>;

  axis?: Axis;

  ngAfterViewInit(): void {
    this.axis = axis(this.properties);
    this.#setProperties(this.axis);
    this.axis.render(this.canvasRef.nativeElement);
  }

  #setProperties(axis: Axis) {
    const inputMappings = this.#getInputToChartMappings(axis);

    Object.entries(inputMappings).forEach(([key, method]) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const value = (this as any)[key];
      if (value !== undefined && method) {
        method.call(axis, value);
      }
    });
  }

  #getInputToChartMappings(
    chart: Axis,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ): Record<string, (arg: any) => Axis> {
    return {
      width: chart.width,
      height: chart.height,
      dpi: chart.dpi,
      background: chart.background,
      position: chart.position,
      font: chart.font,
      fontColor: chart.fontColor,
      lineWidth: chart.lineWidth,
      ticks: chart.ticks,
      tickLength: chart.tickLength,
      tickWidth: chart.tickWidth,
      tickPadding: chart.tickPadding,
    };
  }
}

// packages/react-sparklib/src/lib/axis.tsx
import { useEffect, useRef } from 'react';
import * as sparklib from 'sparklib';

export interface AxisProps {
  position?: sparklib.AxisPosition;
  width?: number;
  height?: number;
  dpi?: number;
  background?:
    | string
    | sparklib.LinearGradient
    | sparklib.LinearGradientBuilder;
  lineWidth?: number;
  font?: string; // 'bold 12px Arial'
  fontColor?: string;
  ticks?: sparklib.AxisTick[];
  tickLength?: number;
  tickWidth?: number;
  tickPadding?: number; // space between text label and tick mark
  properties?: sparklib.AxisChartProperties;
}

export const Axis = (props: AxisProps) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const axis = sparklib.axis(props.properties);

    const setChartProperties = (axis: sparklib.Axis) => {
      const inputMappings = getInputToChartMappings(axis);

      Object.entries(inputMappings).forEach(([key, method]) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const value = (props as any)[key];
        if (value !== undefined && method) {
          method.call(axis, value);
        }
      });
    };

    const getInputToChartMappings = (
      axis: sparklib.Axis,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ): Record<string, (arg: any) => sparklib.Axis> => {
      return {
        width: axis.width,
        height: axis.height,
        dpi: axis.dpi,
        background: axis.background,
        position: axis.position,
        font: axis.font,
        fontColor: axis.fontColor,
        lineWidth: axis.lineWidth,
        ticks: axis.ticks,
        tickLength: axis.tickLength,
        tickWidth: axis.tickWidth,
        tickPadding: axis.tickPadding,
      };
    };

    if (canvasRef.current) {
      setChartProperties(axis);
      axis.render(canvasRef.current);
    }
  }, [props]);

  return <canvas ref={canvasRef}></canvas>;
};

export default Axis;
