// packages/ngx-sparklib/src/lib/bar-chart.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  BarChart,
  BarChartProperties,
  BarValueType,
  DatumLine,
  LinearGradient,
  LinearGradientBuilder,
  Margins,
  MarginsBuilder,
  Range,
  ValueAccessor,
  barChart,
} from 'sparklib';

@Component({
  selector: 'sparklib-bar-chart',
  standalone: true,
  imports: [CommonModule],
  template:
    '<canvas #canvasRef [style.height.px]="height" style="display: block; margin: 0; padding: 0; border: none;"></canvas>',
  styles: [],
})
export class BarChartComponent<T = unknown>
  implements AfterViewInit, OnDestroy
{
  // mandatory properties
  @Input({ required: true }) values!: BarValueType<T>[];

  // optional value properties
  @Input() xAccessor: ValueAccessor<T>;
  @Input() yAccessor: ValueAccessor<T>;

  // optional properties
  @Input() width?: number;
  @Input() height?: number;
  @Input() dpi?: number;
  @Input() background?: string | LinearGradient | LinearGradientBuilder;
  @Input() barPadding?: number;
  @Input() barWidth?: number;
  @Input() margins?: Partial<Margins> | MarginsBuilder;
  @Input() strokeStyle?: string | LinearGradient | LinearGradientBuilder;
  @Input() fillStyle?: string | LinearGradient | LinearGradientBuilder;
  @Input() yDomain?: Range;
  @Input() yDatumLines?: DatumLine[];
  @Input() properties?: BarChartProperties;

  @ViewChild('canvasRef') canvasRef!: ElementRef<HTMLCanvasElement>;

  barChart?: BarChart<T>;

  ngAfterViewInit(): void {
    this.barChart = barChart<T>(this.properties);
    this.#setChartProperties(this.barChart);
    this.barChart.render(this.values, this.canvasRef.nativeElement);
  }

  ngOnDestroy(): void {
    this.barChart?.dispose();
  }

  #setChartProperties(chart: BarChart<T>) {
    const inputMappings = this.#getInputToChartMappings(chart);

    Object.entries(inputMappings).forEach(([key, method]) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const value = (this as any)[key];
      if (value !== undefined && method) {
        method.call(chart, value);
      }
    });
  }

  #getInputToChartMappings(
    chart: BarChart<T>,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ): Record<string, (arg: any) => BarChart<T>> {
    return {
      // xAccessor: chart.xAccessor,
      // yAccessor: chart.yAccessor,
      // yDomain: chart.yDomain,
      background: chart.background,
      dpi: chart.dpi,
      fillStyle: chart.fillStyle,
      height: chart.height,
      margins: chart.margins,
      width: chart.width,
      yDatumLines: chart.yDatumLines,
    };
  }
}

// packages/react-sparklib/src/lib/bar-chart.tsx
import { useEffect, useRef } from 'react';
import * as sparklib from 'sparklib';

/**
 * Interface representing the properties for the BarChart component.
 *
 * @template T - The type of the data for the chart.
 */
interface BarChartProps<T = unknown> {
  // mandatory properties
  values: sparklib.BarValueType<T>[];

  // TODO: optional value properties
  xAccessor?: sparklib.ValueAccessor<T>;
  yAccessor?: sparklib.ValueAccessor<T>;

  // optional properties
  width?: number;
  height?: number;
  dpi?: number;
  background?:
    | string
    | sparklib.LinearGradient
    | sparklib.LinearGradientBuilder;
  barPadding?: number;
  barWidth?: number;
  margins?: Partial<sparklib.Margins> | sparklib.MarginsBuilder;
  fillStyle?: string | sparklib.LinearGradient | sparklib.LinearGradientBuilder;
  yDomain?: sparklib.Range;
  yDatumLines?: sparklib.DatumLine[];
  properties?: sparklib.BarChartProperties;
}

/**
 * BarChart component renders a canvas-based bar chart using the sparklib library.
 * This component sets up a BarChart instance and attaches necessary event listeners.
 * It also handles the cleanup by disposing of the BarChart instance to prevent memory leaks.
 *
 * @template T - The type of the data for the chart.
 * @param {BarChartProps<T>} props - The properties of the BarChart component.
 * @returns A canvas element configured to display the bar chart.
 */
// prettier-ignore
export const BarChart = <T = unknown>(props: BarChartProps<T>) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const barChart = sparklib.barChart<T>(props.properties);

    const setChartProperties = (chart: sparklib.BarChart<T>) => {
      const inputMappings = getInputToChartMappings(chart);

      Object.entries(inputMappings).forEach(([key, method]) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const value = (props as any)[key];
        if (value !== undefined && method) {
          method.call(chart, value);
        }
      });
    };

    const getInputToChartMappings = (
      chart: sparklib.BarChart<T>,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ): Record<string, (arg: any) => sparklib.BarChart<T>> => {
      return {
        width: chart.width,
        height: chart.height,
        dpi: chart.dpi,
        margins: chart.margins,
        background: chart.background,
        barPadding: chart.barPadding,
        barWidth: chart.barWidth,
        fillStyle: chart.fillStyle,
        // TODO: yDomain: chart.yDomain,
        yDatumLines: chart.yDatumLines,
        // TODO: xAccessor: chart.xAccessor,
        // TODO: yAccessor: chart.yAccessor,
      };
    };

    if (canvasRef.current) {
      setChartProperties(barChart);
      barChart.render(props.values, canvasRef.current);
    }

    return () => {
      barChart.dispose();
    };
  }, [props]);

  return <canvas ref={canvasRef}></canvas>;
};
