// packages/react-sparklib/src/lib/stripe-chart.tsx
import { useEffect, useRef } from 'react';
import * as sparklib from 'sparklib';

export interface StripeChartProps {
  values: number[];
  width?: number;
  height?: number;
  dpi?: number;
  background?:
    | string
    | sparklib.LinearGradient
    | sparklib.LinearGradientBuilder
    | undefined;
  margins?: sparklib.Margins | sparklib.MarginsBuilder;
  gradientColors?: string[];
  nGradientColorLevels?: number;
  domain?: sparklib.Range | undefined;
  properties?: sparklib.StripeChartProperties;
}

export const StripeChart = (props: StripeChartProps) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const chart = sparklib.stripeChart(props.properties);

    const setChartProperties = (chart: sparklib.StripeChart) => {
      const inputMappings = getInputToChartMappings(chart);

      Object.entries(inputMappings).forEach(([key, method]) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const value = (props as any)[key];
        if (value !== undefined && method) {
          method.call(chart, value);
        }
      });
    };

    if (canvasRef.current) {
      setChartProperties(chart);
      chart.render(props.values, canvasRef.current);
    }
  }, [props]);

  const getInputToChartMappings = (
    chart: sparklib.StripeChart,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ): Record<string, (arg: any) => sparklib.StripeChart> => {
    return {
      width: chart.width,
      height: chart.height,
      dpi: chart.dpi,
      margins: chart.margins,
      background: chart.background,
      gradientColors: chart.gradientColors,
      nGradientColorLevels: chart.nGradientColorLevels,
      domain: chart.domain,
    };
  };

  return <canvas ref={canvasRef}></canvas>;
};

export default StripeChart;

// packages/ngx-sparklib/src/lib/stripe-chart.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  LinearGradient,
  LinearGradientBuilder,
  Margins,
  MarginsBuilder,
  StripeChart,
  StripeChartProperties,
  stripeChart,
} from 'sparklib';

@Component({
  selector: 'sparklib-stripe-chart',
  standalone: true,
  imports: [CommonModule],
  template: '<canvas #canvasRef></canvas>',
  styles: [],
})
export class StripeChartComponent implements AfterViewInit {
  // mandatory properties
  @Input({ required: true }) values!: number[];
  // optional properties
  @Input() width?: number;
  @Input() height?: number;
  @Input() dpi?: number;
  @Input() background?: string | LinearGradient | LinearGradientBuilder;
  @Input() margins?: Partial<Margins> | MarginsBuilder;
  @Input() properties?: StripeChartProperties;

  @ViewChild('canvasRef') canvasRef!: ElementRef<HTMLCanvasElement>;

  ngAfterViewInit(): void {
    const chart = stripeChart(this.properties);
    this.#setChartProperties(chart);
    chart.render(this.values, this.canvasRef.nativeElement);
  }

  #setChartProperties(chart: StripeChart) {
    const inputMappings = this.#getInputToChartMappings(chart);

    Object.entries(inputMappings).forEach(([key, method]) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const value = (this as any)[key];
      if (value !== undefined && method) {
        method.call(chart, value);
      }
    });
  }

  #getInputToChartMappings(
    chart: StripeChart,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ): Record<string, (arg: any) => StripeChart> {
    return {
      width: chart.width,
      height: chart.height,
      dpi: chart.dpi,
      margins: chart.margins,
      background: chart.background,
    };
  }
}
